export const natureOfBusinessItems = [
  { label: "Accountancy Firm", value: "Accountancy firm" },
  { label: "Agriculture", value: "Agriculture" },
  { label: "Antique Dealer", value: "Antique Dealer" },
  { label: "Arms Dealer", value: "Arms Dealer" },
  { label: "Art Dealer", value: "Art Dealer" },
  { label: "Banking", value: "Banking" },
  { label: "Barber / Parlour / Salon", value: "Barber,Parlour,Salon" },
  { label: "Brokerage", value: "Brokerage" },
  { label: "Bullion Dealer and Jeweller", value: "Bullion Dealer and Jeweller" },
  { label: "Casino / Gaming", value: "Casino,Gaming Application" },
  { label: "Educational Institute", value: "Educational Institute" },
  { label: "Financial Institution", value: "Financial Institution" },
  { label: "Healthcare / Pharma", value: "Healthcare,Pharma" },
  { label: "Import And Export Trader", value: "Import And Export Trader" },
  { label: "Kirana Shop", value: "Kirana shop" },
  { label: "Law", value: "Law" },
  { label: "Liquor", value: "Liquor" },
  { label: "Logistics", value: "Logistics" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "Marketing / Multi-level Marketing", value: "Marketing including Multi-level Marketing" },
  { label: "Media", value: "Media" },
  { label: "Mobility", value: "Mobility" },
  { label: "Money Changer", value: "Money Changer" },
  { label: "Money Lender", value: "Money Lender" },
  { label: "Pawn Shop", value: "Pawn Shop" },
  { label: "Real Estate", value: "Real Estate" },
  { label: "Restaurant and Hospitality", value: "Restaurant and Hospitality" },
  { label: "Retail Shop", value: "Retail Shop" },
  { label: "Service Provider", value: "Service Provider" },
  { label: "Small Vendor", value: "Small vendor" },
  { label: "Stock Trading", value: "Stock Trading" },
  { label: "Transport", value: "Transport" },
  { label: "Wholesale Trading", value: "Wholesale Trading" },
  { label: "Others", value: "Others" },
];